[build-system]
requires = ["setuptools>=64", "setuptools_scm>=8"]
build-backend = "setuptools.build_meta"

[project]
name = "pipeliner"
dynamic = ["version"]
requires-python = ">= 3.11"

dependencies = [
  "pydantic",
  "sagemaker",
  "boto3",
]

[project.optional-dependencies]
local = [
  "sagemaker[local]",
]

[tool.setuptools.dynamic]
version = {attr = "pipeliner.__VERSION__"}