[build-system]
requires = ["setuptools>=64", "setuptools_scm>=8"]
build-backend = "setuptools.build_meta"

[project]
name = "pipeliner"
dynamic = ["version"]
requires-python = ">= 3.11"

dependencies = ["pydantic", "sagemaker", "boto3", "scikit-learn", "torch", "scipy"]

[project.optional-dependencies]
testing = [
    "pytest",
    "pytest-cov",
    "pytest-mock",
    "sagemaker[local]",
    "matplotlib",
    "seaborn",
]

[tool.setuptools.dynamic]
version = { attr = "pipeliner.__VERSION__" }

[tool.setuptools.packages.find]
where = ["src"]
exclude = ["tests", "notebooks"]

[tool.pytest.ini_options]
testpaths = "tests"
addopts = ["--cov=src", "--cov-report=html", "-s"]

[tool.coverage.run]
branch = true
source = ["src"]

[tool.coverage.report]
fail_under = 95
skip_empty = true
