name: 'Pytest'
description: 'Runs pytest'

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true

    - name: Install dependencies
      run: uv sync --dev
      shell: bash

    - name: Test with pytest
      run: uv run pytest
      shell: bash