name: pytest

on: [push]

jobs:
  build:
    name: Pytest
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true

    - name: Install dependencies
      run: uv sync --extra testing

    - name: Test with pytest
      run: uv run pytest

    - name: Build distribution package
      run: uv build --no-cache
