name: pytest

on: [push]

jobs:
  build:
    name: Pytest
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[testing]

    - name: Test with pytest
      run: pytest

    - name: Install uv
      uses: astral-sh/setup-uv@v5

    - name: Build distribution package
      run: uv build --no-cache
